version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: drug-indication-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: drug-indication-service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - drug-indication-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for caching (optional)
  redis:
    image: redis:7.2-alpine
    container_name: drug-indication-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - drug-indication-network

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: drug-indication-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://admin:password123@mongo:27017/drug-indication-service?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_TTL: 3600
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRES_IN: 7d
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - drug-indication-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production API Service
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: drug-indication-api-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://admin:password123@mongo:27017/drug-indication-service?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_TTL: 3600
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 7d
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      LOG_LEVEL: info
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - drug-indication-network
    profiles:
      - production

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  drug-indication-network:
    driver: bridge 